### ISSUE TITLE
The type definitions have (overriding/masking/type incompatibility) issue

### ISSUE THREAD

**Issue by rk-7** [leozhao0709/express-flash-message#1]
During compilation with typescript the following issue occurs:

node_modules/express-flash-message/dist/index.d.ts(8,13): error TS2717: Subsequent property declarations must have the same type.  Property 'flash'
must be of type '{ (): { [key: string]: string[]; }; (message: string): any; (event: string, message: string): any; }', but here has type '(event: string, message: string) => Promise<void>'.

**Comment by leozhao9527** [comment]
@rk-7  I don't see this error when I build. Did you use any other flash message package at the same time? Just from this error message, looks like some other part that also defines request.flash type.

**Comment by leizhao-coupa** [comment]
close this one as no response any more...
