### ISSUE TITLE
Does this work with cookie sessions? + Promise not resolving

### ISSUE THREAD

**Issue by LeanKhan** [leozhao0709/express-flash-message#3]
Hello, in my project I am using cookie sessions. When I try to set a flash message the promise never resolves. Please what is the issue? Thank you.

**Comment by leozhao9527** [comment]
@LeanKhan By default, the old version won't work with `cookie session`. But I just publish a new version, you can pass `useCookieSession` now, then the promise should resolve. The documentation is also just updating, you can use it this way:

`app.use(flash({ sessionKeyName: 'flashMessage', useCookieSession: true }));`

**Comment by LeanKhan** [comment]
I have seen the changes! They work well. Thank you very much. I appreciate the quick response, you will go far 🙏
