### ISSUE TITLE
How to handle both info and error messages at the same time

### ISSUE THREAD

**Issue by dtrikannad** [leozhao0709/express-flash-message#6]
I'm unable to do the following. It appears to clear all messages once consumeFlash is called for ('info') so that consumeFlash('error') is empty. Is there a way to just clear it for the one key?

```
  await req.flash('info', 'welcome');
  await req.flash('error', 'welcome message');
  await req.flash('error', 'error 2nd message');
```

and then retrieve it like

```
  let info = await req.consumeFlash('info');
  let error = await req.consumeFlash('error');
```

**Comment by leozhao9527** [comment]
@dtrikannad Yes, that's possible. Let me create a new version to add this feature.

**Comment by leozhao9527** [comment]
Should be fixed at this pr: https://github.com/leozhao0709/express-flash-message/pull/7 and please try `2.1.0` version.
